backend:
  name: github
  repo: erofteev/mitosite-decap
  branch: main

locale: 'ru'
#logo_url:

#publish_mode: editorial_workflow

media_folder: "site/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "blog"
    label: "Блог"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Описание", name: "description", widget: "string"}
      - {label: "Автор", name: "author", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      #- {label: "Изображение", name: "image", widget: "image"}
      - {label: "Содержание", name: "body", widget: "markdown"}
  #- name: "programs"
  #  label: "Программы"
  #  folder: "src/programs"
  #  create: true
  #  fields:
  #    - {label: "Заголовок", name: "title", widget: "string"}
  #    - {label: "Содержание", name: "body", widget: "markdown"}
