backend:
  name: git-gateway
  repo: erofteev/mitosite-decap
  ranch: master
media_folder: "site/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      #- {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  #- name: "programs"
  #  label: "Program"
  #  folder: "src/programs"
  #  create: true
  #  fields:
  #    - {label: "Title", name: "title", widget: "string"}
  #    - {label: "Body", name: "body", widget: "markdown"}
